Description: This template creates Linux instances

Parameters:

  InstanceImageId:
    Description: AMI ID for Instance
    Type: String
    Default: ami-06489866022e12a14 #add ami id

  InstanceType:
    Description: Instance type for Instance
    Type: String
    Default: t2.micro #add instance type

  SubnetId:
    Description: Subnet ID for Instance
    Type: String
    Default: subnet-7228d619 #add subnet Id

  SecurityGroupIds:
    Description: Security Group ID for Instance
    Type: String
    Default: sg-03c7c94a1e0363593 #add Security Group Id

  # InstanceDataVolumeSize:
  #   Description: Data volume size for Instance
  #   Type: String
  #   Default: #add volume size for data volume

  # InstanceDataVolumeType:
  #   Description: Data volume type for Instance
  #   Type: String
  #   Default: #add data volume type

  InstanceRootVolumeSize:
    Description: Root volume size for Instance
    Type: String
    Default: 8 #add volume size for root volume

  InstanceRootVolumeType:
    Description: Root volume type for Instance
    Type: String
    Default: gp3 #add root volume type 

Resources:

  InstanceA:
      Type: AWS::EC2::Instance
      Properties:
        Tags:
            - Key: Name
              Value: InstanceA
            - Key: user
              Value: Unny
            - Key: project
              Value: research  
        SubnetId: !Ref SubnetId
        ImageId: !Ref InstanceImageId
        InstanceType: !Ref InstanceType 
        SecurityGroupIds: 
          - !Ref SecurityGroupIds
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              VolumeSize: !Ref InstanceRootVolumeSize
              VolumeType: !Ref InstanceRootVolumeType
              DeleteOnTermination: true
              Encrypted: true
        UserData:
          Fn::Base64: !Sub |

            #!/bin/bash
            # Use this for your user data (script from top to bottom)
            # install httpd (Linux 2 version)
            yum update -y
            yum install -y httpd
            systemctl start httpd
            systemctl enable httpd
            echo "<h1>Hello World from $(hostname -f)</h1>" > /var/www/html/index.html


  # InstanceDataVolume:
  #   Type: AWS::EC2::Volume
  #   Properties:
  #     Size: !Ref InstanceDataVolumeSize
  #     Encrypted: true
  #     AvailabilityZone: !Select [0, !GetAZs ""]
  #     VolumeType: !Ref InstanceDataVolumeType
  #     Tags:
  #       - Key: Name
  #         Value: Instance DataVolume
  #       - Key: user
  #         Value: coderman
  #       - Key: project
  #         Value: research

  # InstanceDataVolumeAttachment:
  #   Type: AWS::EC2::VolumeAttachment
  #   Properties:
  #     InstanceId: !Ref  InstanceA
  #     VolumeId: !Ref InstanceDataVolume
  #     Device: /dev/sdb